spring.application.name=wattzybackend
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/wattzy
spring.datasource.username=postgres
spring.datasource.password=sql123

jwt.secret=JYrKyCzzma9W4vRla6iln9mBm2kehtJIa6gvugBadasdasdFsrs6oaVuyZ1bp8XXK1DZ6Zl1BYU1NJn00vBJrN8